CREATE TABLE IF NOT EXISTS pickup_points (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider VARCHAR(40) NOT NULL,
    name VARCHAR(120) NOT NULL,
    address VARCHAR(255) NOT NULL,
    phone VARCHAR(40),
    work_hours VARCHAR(120),
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL,
    logo_url VARCHAR(600),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    CONSTRAINT uq_pickup_provider_name UNIQUE (provider, name)
);

ALTER TABLE orders
    ADD COLUMN IF NOT EXISTS pickup_point_id BIGINT;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conname = 'fk_orders_pickup_point'
    ) THEN
        ALTER TABLE orders
            ADD CONSTRAINT fk_orders_pickup_point
            FOREIGN KEY (pickup_point_id) REFERENCES pickup_points (id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_pickup_points_provider ON pickup_points(provider);
CREATE INDEX IF NOT EXISTS idx_orders_pickup_point_id ON orders(pickup_point_id);
